// Generates typed AnyCable client code from the cable AsyncAPI documents.
//
// For each configured document it emits, under the output directory:
//   models/*.ts        — message payload interfaces + enums (via @asyncapi/modelina)
//   channels/*.ts      — one `Channel<Params, Message>` subclass per operation;
//                        depends ONLY on @anycable/core (platform-agnostic — works
//                        on web AND React Native) + the models. Together with
//                        models/ this is the portable, app-free core.
//   runtime.ts         — the framework preset's subscribe+lifecycle helper. The
//                        ONLY file with the cable seam: it imports the cable
//                        provider from a CONFIGURABLE path (Orval-mutator style).
//   composables/*.ts   — per-channel `useXChannel(handlers)` sugar delegating to
//                        runtime; imports only ../runtime + its own class.
//   index.ts           — barrel re-exporting everything
//
// The framework preset is per-target (`output.preset`, default "vue"): "vue"
// emits Vue composables (onScopeDispose); "react" emits React hooks (useEffect)
// for React Native / React consumers. Only the preset (runtime + wrapper) differs
// — the channel classes + models are shared across presets.
//
// Targets (inputs, output dirs, cable seam, preset) come from a cable.config file
// in the consuming project — the AnyCable analog of orval.config.ts. The CLI
// (bin/cli.mjs) loads that config and calls generateAll(); generateOne/generateAll
// are also exported for programmatic use.
import {
  TypeScriptFileGenerator,
  typeScriptDefaultPropertyKeyConstraints,
} from "@asyncapi/modelina";
import { Parser } from "@asyncapi/parser";
import fs from "node:fs/promises";
import path from "node:path";

/** Fallback cable seam when a target omits `output.cable`. */
const DEFAULT_CABLE = { path: "../internalCableClient", name: "getCable" };

const BANNER =
  "// AUTO-GENERATED by asyncapi-cable from the cable AsyncAPI documents.\n" +
  "// Do not edit by hand — regenerate with the asyncapi-cable CLI.\n";

const CHANNEL_HANDLERS = `type ChannelMessage<C> = C extends Channel<infer _P, infer M> ? M : never;

export interface ChannelHandlers<M> {
  onMessage: (data: M) => void;
  onConnect?: () => void;
  onDisconnect?: () => void;
}`;

/** The generated runtime — the one file that references the cable seam. Per preset. */
function renderRuntime(cable, preset) {
  if (preset === "react") {
    return `${BANNER}
import type { Channel } from "@anycable/core";
import { useEffect, useRef } from "react";
import { ${cable.name} } from "${cable.path}";

${CHANNEL_HANDLERS}

/**
 * Subscribe a channel for the lifetime of the component. \`factory\` builds the
 * channel; handlers are read through a ref so re-renders don't resubscribe.
 */
export function useChannelSubscription<C extends Channel>(
  factory: () => C,
  handlers: ChannelHandlers<ChannelMessage<C>>,
): void {
  const handlersRef = useRef(handlers);
  handlersRef.current = handlers;

  useEffect(() => {
    const channel = factory();
    ${cable.name}().subscribe(channel);
    const unbind = [
      channel.on("message", (data) =>
        handlersRef.current.onMessage(data as ChannelMessage<C>)
      ),
      channel.on("connect", () => handlersRef.current.onConnect?.()),
      channel.on("disconnect", () => handlersRef.current.onDisconnect?.()),
    ];
    return () => {
      unbind.forEach((off) => off());
      channel.disconnect();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
}
`;
  }

  return `${BANNER}
import type { Channel } from "@anycable/core";
import { getCurrentScope, onScopeDispose } from "vue";
import { ${cable.name} } from "${cable.path}";

${CHANNEL_HANDLERS}

/** Subscribe a channel via the app cable and tear it down with the effect scope. */
export function subscribeChannel<C extends Channel>(
  channel: C,
  handlers: ChannelHandlers<ChannelMessage<C>>,
): C {
  ${cable.name}().subscribe(channel);
  channel.on("message", (data) => handlers.onMessage(data as ChannelMessage<C>));
  if (handlers.onConnect) channel.on("connect", handlers.onConnect);
  if (handlers.onDisconnect) channel.on("disconnect", handlers.onDisconnect);
  if (getCurrentScope()) onScopeDispose(() => channel.disconnect());
  return channel;
}
`;
}

async function parseDocument(absInput) {
  const parser = new Parser();
  const raw = await fs.readFile(absInput, "utf8");
  const { document, diagnostics } = await parser.parse(raw);
  if (!document) {
    const errors = diagnostics
      .filter((d) => d.severity === 0)
      .map((d) => `  - ${d.message} (${d.path?.join("/")})`)
      .join("\n");
    throw new Error(`Failed to parse ${absInput}:\n${errors}`);
  }
  return document;
}

/**
 * The message schemas carry an `allOf`/`if`/`then` block encoding "if `exception`
 * is present then `status` is `failed`". That constraint is not representable in
 * TypeScript, and Modelina mis-flattens the `then` branch into the base schema
 * (turning `status: string` into the literal `'failed'`). Strip conditionals so
 * the generated types reflect the unconstrained shape.
 */
export function stripConditionals(json) {
  const schemas = json?.components?.schemas ?? {};
  for (const schema of Object.values(schemas)) {
    if (Array.isArray(schema.allOf)) {
      schema.allOf = schema.allOf.filter(
        (sub) => !("if" in sub || "then" in sub || "else" in sub)
      );
      if (schema.allOf.length === 0) delete schema.allOf;
    }
    delete schema.if;
    delete schema.then;
    delete schema.else;
  }
  return json;
}

/** Collapse duplicate `| null`/`| undefined` union members Modelina emits for nullable type arrays. */
export function dedupeUnions(source) {
  return source.replace(
    /^(\s*[\w"']+\??:\s*)(.+);$/gm,
    (line, prefix, type) => {
      if (!type.includes(" | ")) return line;
      const seen = new Set();
      const parts = type.split(" | ").filter((part) => {
        if (seen.has(part)) return false;
        seen.add(part);
        return true;
      });
      return `${prefix}${parts.join(" | ")};`;
    }
  );
}

export function tidyModelSource(source) {
  let out = dedupeUnions(source)
    // Represent `additionalProperties: true` as a real index signature.
    .replace(
      /^\s*additionalProperties\?: Record<string, any>;$/m,
      "  [key: string]: unknown;"
    )
    .trimStart();
  // Interfaces and type aliases are type-only; `isolatedModules` requires
  // `export type` for their re-export. Enums are values — leave those alone.
  if (!/\benum\s+\w+/.test(out)) {
    out = out.replace(/^export \{ (\w+) \};?$/m, "export type { $1 };");
  }
  return out;
}

async function generateModels(document, absModelsDir) {
  const generator = new TypeScriptFileGenerator({
    modelType: "interface",
    mapType: "record",
    // Preserve the snake_case wire keys (user_id, error_message) instead of
    // camelizing — cable payloads are not transformed on the socket path.
    // Keep the default reserved-word/special-char safety, override only casing.
    constraints: {
      propertyKey: typeScriptDefaultPropertyKeyConstraints({
        NAMING_FORMATTER: (name) => name,
        // Interface property names may be any string; keeping wire keys like
        // `status`/`name` verbatim is safe and required to match the payload.
        NO_RESERVED_KEYWORDS: (name) => name,
      }),
    },
  });
  const input = stripConditionals(structuredClone(document.json()));
  const models = await generator.generateToFiles(input, absModelsDir, {
    exportType: "named",
  });

  for (const model of models) {
    const file = path.join(absModelsDir, `${model.modelName}.ts`);
    const src = await fs.readFile(file, "utf8");
    await fs.writeFile(file, `${BANNER}\n${tidyModelSource(src)}`);
  }

  return models.map((m) => m.modelName);
}

/** Read an `x-` extension off a parser node, tolerating either json() or the extensions API. */
function extension(node, name) {
  const fromJson = node.json?.()?.[name];
  if (fromJson !== undefined) return fromJson;
  return node.extensions?.().get?.(name)?.value?.();
}

/** Build the TS type for the params the client passes at subscribe time (AsyncAPI 3.0 params are strings). */
export function clientParamsType(channelJson) {
  const params = channelJson?.parameters ?? {};
  const clientParams = Object.keys(params).filter(
    (name) => params[name]?.["x-client-supplied"] !== false
  );
  if (clientParams.length === 0) return "Record<string, never>";
  return `{ ${clientParams.map((name) => `${name}: string`).join("; ")} }`;
}

/**
 * Render the portable AnyCable channel class. Pure — depends only on
 * @anycable/core + the generated message types, so it is extractable and works
 * on any platform (web, React Native).
 */
export function renderChannelClass({
  channelName,
  identifier,
  paramsType,
  messageNames,
}) {
  const className = `${channelName}Channel`;
  const dataType = `${channelName}Data`;
  const paramsName = `${channelName}Params`;
  const modelImports = messageNames
    .map((name) => `import type { ${name} } from "../models/${name}";`)
    .join("\n");

  const source = `${BANNER}
import { Channel } from "@anycable/core";
${modelImports}

/** Alternatives declared for the operation — AsyncAPI treats a channel's messages as a union. */
export type ${dataType} = ${messageNames.join(" | ")};

/** Params the client supplies at subscribe time. */
export type ${paramsName} = ${paramsType};

export class ${className} extends Channel<${paramsName}, ${dataType}> {
  static identifier = "${identifier}";
}
`;

  return { className, dataType, paramsName, source };
}

/** Render the per-channel Vue composable — thin sugar over runtime.subscribeChannel. */
export function renderComposable({
  channelName,
  className,
  dataType,
  paramsName,
  hasParams,
  preset,
}) {
  const composableName = `use${channelName}Channel`;
  const paramsArg = hasParams ? `params: ${paramsName}, ` : "";
  const paramsPass = hasParams ? "params" : "";

  if (preset === "react") {
    const source = `${BANNER}
import { useChannelSubscription, type ChannelHandlers } from "../runtime";
import { ${className}, type ${dataType} } from "../channels/${className}";

/** Subscribe to ${className} for the lifetime of the component. */
export function ${composableName}(
  ${paramsArg}handlers: ChannelHandlers<${dataType}>,
): void {
  useChannelSubscription(() => new ${className}(${paramsPass}), handlers);
}
`;
    return { composableName, source };
  }

  const source = `${BANNER}
import { subscribeChannel, type ChannelHandlers } from "../runtime";
import { ${className}, type ${dataType} } from "../channels/${className}";

/** Subscribe to ${className} for the lifetime of the current effect scope. */
export function ${composableName}(
  ${paramsArg}handlers: ChannelHandlers<${dataType}>,
): ${className} {
  return subscribeChannel(new ${className}(${paramsPass}), handlers);
}
`;

  return { composableName, source };
}

/** Match an operation message to the Modelina-generated model name for its payload. */
function resolveMessageModelName(message, modelNames) {
  const candidates = [message.id?.(), message.name?.()].filter(Boolean);
  for (const candidate of candidates) {
    if (modelNames.includes(candidate)) return candidate;
  }
  const payload = message.payload?.();
  const payloadId = payload?.id?.() ?? payload?.$id?.();
  if (payloadId && modelNames.includes(payloadId)) return payloadId;
  return candidates[0] ?? payloadId;
}

/** Emit a portable channel class + a per-channel composable/hook per `receive` operation. */
async function generateChannels(
  document,
  absChannelsDir,
  absComposablesDir,
  modelNames,
  preset
) {
  await fs.mkdir(absChannelsDir, { recursive: true });
  await fs.mkdir(absComposablesDir, { recursive: true });
  const emitted = [];

  for (const operation of document.operations().all()) {
    if (operation.action() !== "receive") continue;

    const channel = operation.channels().all()[0];
    const channelName = channel.id();
    const channelJson = channel.json();
    const identifier =
      extension(channel, "x-actioncable-channel") ?? `${channelName}Channel`;
    const paramsType = clientParamsType(channelJson);
    const hasParams = paramsType !== "Record<string, never>";

    const messageNames = operation
      .messages()
      .all()
      .map((message) => resolveMessageModelName(message, modelNames))
      .filter(Boolean);

    const cls = renderChannelClass({
      channelName,
      identifier,
      paramsType,
      messageNames,
    });
    await fs.writeFile(
      path.join(absChannelsDir, `${cls.className}.ts`),
      cls.source
    );

    const comp = renderComposable({
      channelName,
      className: cls.className,
      dataType: cls.dataType,
      paramsName: cls.paramsName,
      hasParams,
      preset,
    });
    await fs.writeFile(
      path.join(absComposablesDir, `${comp.composableName}.ts`),
      comp.source
    );

    emitted.push({
      className: cls.className,
      composableName: comp.composableName,
    });
  }

  return emitted;
}

async function writeBarrel(absOutDir, modelNames, channels) {
  const lines = [
    ...modelNames.map((name) => `export * from "./models/${name}";`),
    ...channels.map((c) => `export * from "./channels/${c.className}";`),
    'export * from "./runtime";',
    ...channels.map(
      (c) => `export * from "./composables/${c.composableName}";`
    ),
  ];
  await fs.writeFile(
    path.join(absOutDir, "index.ts"),
    `${BANNER}\n${lines.join("\n")}\n`
  );
}

export async function generateOne({
  input,
  outDir,
  cable = DEFAULT_CABLE,
  preset = "vue",
  cwd = process.cwd(),
}) {
  // `path.resolve` passes absolute paths through, so tests can target a tmp dir.
  const absInput = path.resolve(cwd, input);
  const absOutDir = path.resolve(cwd, outDir);

  await fs.rm(absOutDir, { recursive: true, force: true });
  await fs.mkdir(path.join(absOutDir, "models"), { recursive: true });

  const document = await parseDocument(absInput);
  const modelNames = await generateModels(
    document,
    path.join(absOutDir, "models")
  );
  const channels = await generateChannels(
    document,
    path.join(absOutDir, "channels"),
    path.join(absOutDir, "composables"),
    modelNames,
    preset
  );
  await fs.writeFile(
    path.join(absOutDir, "runtime.ts"),
    renderRuntime(cable, preset)
  );
  await writeBarrel(absOutDir, modelNames, channels);

  console.info(
    `[asyncapi-cable] ${input} -> ${outDir} ` +
      `(${modelNames.length} models, ${channels.length} channels, ${preset})`
  );
}

/** Generate every target in a config object (see cable.config.mjs), resolving paths against `cwd`. */
export async function generateAll(config, cwd = process.cwd()) {
  for (const target of Object.values(config)) {
    await generateOne({
      input: target.input,
      outDir: target.output.target,
      cable: target.output.cable ?? DEFAULT_CABLE,
      preset: target.output.preset ?? "vue",
      cwd,
    });
  }
}
